name: CI/CD to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build .NET
        run: dotnet build --configuration Release --no-restore

      - name: Run .NET tests
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true

      # ✅ Heroku CLI ni o‘rnatish
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          export PATH="$PATH:/usr/local/bin"

      # ✅ Deploy qilish
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "asilbekpersonal@gmail.com"
          usedocker: false

      # ✅ Ma’lumotlar bazasiga migration qilish
      - name: Run database migrations
        run: |
          heroku run dotnet ef database update --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
